# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: practica_1_development # name your development app something
  host: localhost
  pool: 5
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: practica_1_test # name your development app something
  host: localhost
  pool: 5
  port: 5432
